export enum FlowerColorEnum {
    RED = "RED",
    ORANGE = "ORANGE",
    YELLOW = "YELLOW",
    GREEN = "GREEN",
    BLUE = "BLUE",
    INDIGO = "INDIGO",
    PURPLE = "PURPLE",
    PINK = "PINK",
    WHITE = "WHITE",
    BROWN = "BROWN",
    BLACK = "BLACK",
    MULTICOLORED = "MULTICOLORED",
    ALLCOLORS = "ALLCOLORS"
    // RED,
    // ORANGE,
    // YELLOW,
    // GREEN,
    // BLUE,
    // INDIGO,
    // PURPLE,
    // PINK,
    // WHITE,
    // BROWN,
    // BLACK,
    // MULTICOLORED,
    // ALLCOLORS
}
